- name: Install nginix
  hosts: dev
  become: yes
  tasks:
    - name: Install nginix
      yum:
        name: nginix
        state: present
    
    - name: Start nginix
      service:
        name: nginix
        state: started

# ansible-playbook ansible-playbook.yaml